name: maptest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0-pre

  xt_ui: 
  # path: ../pkg_xt_ui
    git:
      url: https://github.com/evs2bu500/pkg_xt_ui.git
  xt_util: 
    # path: ../pkg_xt_util
    git:
      url: https://github.com/evs2bu500/pkg_xt_util.git   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
