final List<Map<String, dynamic>> stationsCC = [
  {
    'code': 'CE1',
    'name': 'Bayfront',
    'site_tag': 'smrt_bayfront',
    'coord': [0.115, 0.365],
  },
  {
    'code': 'CE2',
    'name': 'Marina Bay',
    'site_tag': 'smrt_marina_bay',
    'coord': [0.085, 0.400],
  },
  {
    'code': 'CC1',
    'name': 'Dhoby Ghaut',
    'site_tag': 'smrt_dhoby_ghaut',
    'coord': [-0.000, 0.175],
  },
  {
    'code': 'CC2',
    'name': 'Bras Basah',
    'site_tag': 'smrt_bras_basah',
    'coord': [0.030, 0.215],
  },
  {
    'code': 'CC3',
    'name': 'Esplanade',
    'site_tag': 'smrt_esplanade',
    'coord': [0.085, 0.290],
  },
  {
    'code': 'CC4',
    'name': 'Promenade',
    'site_tag': 'smrt_promenade',
    'coord': [0.160, 0.310],
  },
  {
    'code': 'CC5',
    'name': 'Nicoll Highway',
    'site_tag': 'smrt_nicoll_highway',
    'coord': [0.167, 0.262],
  },
  {
    'code': 'CC6',
    'name': 'Stadium',
    'site_tag': 'smrt_stadium',
    'coord': [0.180, 0.214],
  },
  {
    'code': 'CC7',
    'name': 'Mountbatten',
    'site_tag': 'smrt_mountbatten',
    'coord': [0.185, 0.166],
  },
  {
    'code': 'CC8',
    'name': 'Dakota',
    'site_tag': 'smrt_dakota',
    'coord': [0.193, 0.118],
  },
  {
    'code': 'CC9',
    'name': 'Paya Lebar',
    'site_tag': 'smrt_paya_lebar',
    'coord': [0.199, 0.070],
  },
  {
    'code': 'CC10',
    'name': 'MacPherson',
    'site_tag': 'smrt_macpherson',
    'coord': [0.185, 0.008],
  },
  {
    'code': 'CC11',
    'name': 'Tai Seng',
    'site_tag': 'smrt_tai_seng',
    'coord': [0.155, -0.038],
  },
  {
    'code': 'CC12',
    'name': 'Bartley',
    'site_tag': 'smrt_bartley',
    'coord': [0.123, -0.084],
  },
  {
    'code': 'CC13',
    'name': 'Serangoon',
    'site_tag': 'smrt_tai_seng',
    'coord': [0.093, -0.130],
  },
  {
    'code': 'CC14',
    'name': 'Lorong Chuan',
    'site_tag': 'smrt_lorong_chuan',
    'coord': [0.030, -0.160],
  },
  {
    'code': 'CC15',
    'name': 'Bishan',
    'site_tag': 'smrt_bishan',
    'coord': [-0.016, -0.165],
  },
  {
    'code': 'CC16',
    'name': 'Marymount',
    'site_tag': 'smrt_marymount',
    'coord': [-0.080, -0.150],
  },
  {
    'code': 'CC17',
    'name': 'Caldecott',
    'site_tag': 'smrt_caldecott',
    'coord': [-0.135, -0.125],
  },
  {
    'code': 'CC19',
    'name': 'Botanic Gardens',
    'site_tag': 'smrt_botanic_gardens',
    'coord': [-0.200, -0.043],
  },
  {
    'code': 'CC20',
    'name': 'Farrer Road',
    'site_tag': 'smrt_farrer_road',
    'coord': [-0.205, 0.010],
  },
  {
    'code': 'CC21',
    'name': 'Holland Village',
    'site_tag': 'smrt_holland_village',
    'coord': [-0.220, 0.070],
  },
  {
    'code': 'CC22',
    'name': 'Buona Vista',
    'site_tag': 'smrt_buona_vista',
    'coord': [-0.225, 0.120],
  },
  {
    'code': 'CC23',
    'name': 'One North',
    'site_tag': 'smrt_one_north',
    'coord': [-0.220, 0.190],
  },
  {
    'code': 'CC24',
    'name': 'Kent Ridge',
    'site_tag': 'smrt_kent_ridge',
    'coord': [-0.215, 0.225],
  },
  {
    'code': 'CC25',
    'name': 'Haw Par Villa',
    'site_tag': 'smrt_har_par_villa',
    'coord': [-0.205, 0.260],
  },
  {
    'code': 'CC26',
    'name': 'Pasir Panjang',
    'site_tag': 'smrt_pasir_panjang',
    'coord': [-0.190, 0.295],
  },
  {
    'code': 'CC27',
    'name': 'Labrador Park',
    'site_tag': 'smrt_labrador_park',
    'coord': [-0.175, 0.330],
  },
  {
    'code': 'CC28',
    'name': 'Telok Blangah',
    'site_tag': 'smrt_telok_blangah',
    'coord': [-0.145, 0.365],
  },
  {
    'code': 'CC29',
    'name': 'HarbourFront',
    'site_tag': 'smrt_harbourfront',
    'coord': [-0.120, 0.405],
  },
];
