const List<Map<String, dynamic>> stationsEW = [
  {
    'code': 'EW1',
    'name': 'Pasir Ris',
    'site_tag': 'smrt_pasir_ris',
    'coord': [0.364, -0.182],
  },
  {
    'code': 'EW2',
    'name': 'Tampines',
    'site_tag': 'smrt_tampines',
    'coord': [0.364, -0.145],
  },
  {
    'code': 'EW3',
    'name': 'Simei',
    'site_tag': 'smrt_simei',
    'coord': [0.364, -0.113],
  },
  {
    'code': 'EW4',
    'name': 'Tanah Merah',
    'site_tag': 'smrt_tanah_merah',
    'coord': [0.364, -0.065],
  },
  {
    'code': 'EW5',
    'name': 'Bedok',
    'site_tag': 'smrt_bedok',
    'coord': [0.285, -0.055],
  },
  {
    'code': 'EW6',
    'name': 'Kembangan',
    'site_tag': 'smrt_kembangan',
    'coord': [0.245, -0.015],
  },
  {
    'code': 'EW7',
    'name': 'Eunos',
    'site_tag': 'smrt_eunos',
    'coord': [0.215, 0.025],
  },
  {
    'code': 'EW8',
    'name': 'Paya Lebar',
    'site_tag': 'smrt_paya_lebar',
    'coord': [0.185, 0.065],
  },
  {
    'code': 'EW9',
    'name': 'Aljunied',
    'site_tag': 'smrt_aljunied',
    'coord': [0.160, 0.105],
  },
  {
    'code': 'EW10',
    'name': 'Kallang',
    'site_tag': 'smrt_kallang',
    'coord': [0.130, 0.145],
  },
  {
    'code': 'EW11',
    'name': 'Lavender',
    'site_tag': 'smrt_lavendar',
    'coord': [0.100, 0.185],
  },
  {
    'code': 'EW12',
    'name': 'Bugis',
    'site_tag': 'smrt_bugis',
    'coord': [0.070, 0.215],
  },
  {
    'code': 'EW13',
    'name': 'City Hall',
    'site_tag': 'smrt_city_hall',
    'coord': [0.045, 0.285],
  },
  {
    'code': 'EW14',
    'name': 'Raffles Place',
    'site_tag': 'smrt_raffles_place',
    'coord': [0.045, 0.340],
  },
  {
    'code': 'EW15',
    'name': 'Tanjong Pagar',
    'site_tag': 'smrt_tanjong_pagar',
    'coord': [-0.060, 0.350],
  },
  {
    'code': 'EW16',
    'name': 'Outram Park',
    'site_tag': 'smrt_outram_park',
    'coord': [-0.120, 0.285],
  },
  {
    'code': 'EW17',
    'name': 'Tiong Bahru',
    'site_tag': 'smrt_tiong_bahru',
    'coord': [-0.132, 0.250],
  },
  {
    'code': 'EW18',
    'name': 'Redhill',
    'site_tag': 'smrt_redhill',
    'coord': [-0.152, 0.220],
  },
  {
    'code': 'EW19',
    'name': 'Queenstown',
    'site_tag': 'smrt_queenstown',
    'coord': [-0.172, 0.190],
  },
  {
    'code': 'EW20',
    'name': 'Commonwealth',
    'site_tag': 'smrt_commonwealth',
    'coord': [-0.192, 0.160],
  },
  {
    'code': 'EW21',
    'name': 'Buona Vista',
    'site_tag': 'smrt_buona_vista',
    'coord': [-0.225, 0.134],
  },
  {
    'code': 'EW22',
    'name': 'Dover',
    'site_tag': 'smrt_dover',
    'coord': [-0.264, 0.134],
  },
  {
    'code': 'EW23',
    'name': 'Clementi',
    'site_tag': 'smrt_clementi',
    'coord': [-0.304, 0.134],
  },
  {
    'code': 'EW24',
    'name': 'Jurong East',
    'site_tag': 'smrt_jurong_east',
    'coord': [-0.341, 0.134],
  },
  {
    'code': 'EW25',
    'name': 'Chinese Garden',
    'site_tag': 'smrt_chinse_garden',
    'coord': [-0.381, 0.134],
  },
  {
    'code': 'EW26',
    'name': 'Lakeside',
    'site_tag': 'smrt_lakeside',
    'coord': [-0.421, 0.134],
  },
  {
    'code': 'EW27',
    'name': 'Boonlay',
    'site_tag': 'smrt_boonlay',
    'coord': [-0.447, 0.110],
  },
  {
    'code': 'EW28',
    'name': 'Pioneer',
    'site_tag': 'smrt_pioneer',
    'coord': [-0.447, 0.065],
  },
  {
    'code': 'EW29',
    'name': 'Joo Koon',
    'site_tag': 'smrt_joo_koon',
    'coord': [-0.447, 0.025],
  },
  {
    'code': 'EW30',
    'name': 'Gul Circle',
    'site_tag': 'smrt_gul_circle',
    'coord': [-0.447, -0.020],
  },
  {
    'code': 'EW31',
    'name': 'Tuas Crescent',
    'site_tag': 'smrt_tuas_crescent',
    'coord': [-0.447, -0.065],
  },
  {
    'code': 'EW32',
    'name': 'Tuas West Road',
    'site_tag': 'smrt_tuas_west_road',
    'coord': [-0.447, -0.110],
  },
  {
    'code': 'EW33',
    'name': 'Tuas Link',
    'site_tag': 'smrt_tuas_link',
    'coord': [-0.447, -0.160],
  },
];
