const List<Map<String, dynamic>> stationsEW = [
  {
    'code': 'EW1',
    'name': 'Pasir Ris',
    'site_tag': 'smrt_pasir_ris',
    'coord': [0.364, -0.182],
  },
  {
    'code': 'EW2',
    'name': 'Tampines',
    'site_tag': 'smrt_tampines',
    'coord': [0.364, -0.145],
  },
  {
    'code': 'EW3',
    'name': 'Simei',
    'site_tag': 'smrt_simei',
    'coord': [0.364, -0.145],
  },
  {
    'code': 'EW4',
    'name': 'Simei',
    'site_tag': 'smrt_simei',
    'coord': [0.364, -0.145],
  },
  {
    'code': 'EW5',
    'name': 'Simei',
    'site_tag': 'smrt_simei',
    'coord': [0.364, -0.145],
  },
  {
    'code': 'EW6',
    'name': 'Simei',
    'site_tag': 'smrt_simei',
    'coord': [0.364, -0.145],
  },
  {
    'code': 'EW19',
    'name': 'Queenstown',
    'site_tag': 'smrt_queenstown',
    'coord': [-0.172, 0.190],
  },
  {
    'code': 'EW20',
    'name': 'Commonwealth',
    'site_tag': 'smrt_commonwealth',
    'coord': [-0.192, 0.160],
  },
  {
    'code': 'EW21',
    'name': 'Buona Vista',
    'site_tag': 'smrt_buona_vista',
    'coord': [-0.225, 0.134],
  },
  {
    'code': 'EW22',
    'name': 'Dover',
    'site_tag': 'smrt_dover',
    'coord': [-0.264, 0.134],
  },
  {
    'code': 'EW23',
    'name': 'Clementi',
    'site_tag': 'smrt_clementi',
    'coord': [-0.304, 0.134],
  },
  {
    'code': 'EW24',
    'name': 'Jurong East',
    'site_tag': 'smrt_jurong_east',
    'coord': [-0.341, 0.134],
  },
  {
    'code': 'EW33',
    'name': 'Tuas Link',
    'site_tag': 'smrt_tuas_link',
    'coord': [-0.447, -0.160],
  },
];
