final List<Map<String, dynamic>> stationsNS = [
  {
    'code': 'NS1',
    'name': 'Jurong East',
    'site_tag': 'smrt_jurong_east',
    'coord': [-0.341, 0.110],
  },
  {
    'code': 'NS2',
    'name': 'Bukit Batok',
    'site_tag': 'smrt_bukit_batok',
    'coord': [-0.341, 0.0306],
  },
  {
    'code': 'NS3',
    'name': 'Bukit Gombak',
    'site_tag': 'smrt_bukit_gombak',
    'coord': [-0.341, -0.0488],
  },
  {
    'code': 'NS4',
    'name': 'Choa Chu Kang',
    'site_tag': 'smrt_choa_chu_kang',
    'coord': [-0.341, -0.1282],
  },
  {
    'code': 'NS5',
    'name': 'Yew Tee',
    'site_tag': 'smrt_yew_tee',
    'coord': [-0.341, -0.2076],
  },
  {
    'code': 'NS7',
    'name': 'Kranji',
    'site_tag': 'smrt_kranji',
    'coord': [-0.341, -0.287],
  },
  {
    'code': 'NS8',
    'name': 'Marsiling',
    'site_tag': 'smrt_marsiling',
    'coord': [-0.325, -0.341],
  },
  {
    'code': 'NS9',
    'name': 'Woodlands',
    'site_tag': 'smrt_woodlands',
    'coord': [-0.250, -0.376],
  },
  {
    'code': 'NS10',
    'name': 'Admiralty',
    'site_tag': 'smrt_admiralty',
    'coord': [-0.200, -0.376],
  },
  {
    'code': 'NS11',
    'name': 'Sembawang',
    'site_tag': 'smrt_sembawang',
    'coord': [-0.150, -0.376],
  },
  {
    'code': 'NS12',
    'name': 'Canberra',
    'site_tag': 'smrt_canberra',
    'coord': [-0.100, -0.376],
  },
  {
    'code': 'NS13',
    'name': 'Yishun',
    'site_tag': 'smrt_yishun',
    'coord': [-0.050, -0.341],
  },
  {
    'code': 'NS14',
    'name': 'Khatib',
    'site_tag': 'smrt_khatib',
    'coord': [-0.035, -0.300],
  },
  {
    'code': 'NS15',
    'name': 'Yio Chu Kang',
    'site_tag': 'smrt_yio_chu_kang',
    'coord': [-0.030, -0.260],
  },
  {
    'code': 'NS16',
    'name': 'Ang Mo Kio',
    'site_tag': 'smrt_ang_mo_kio',
    'coord': [-0.030, -0.210],
  },
  {
    'code': 'NS17',
    'name': 'Bishan',
    'site_tag': 'smrt_bishan',
    'coord': [-0.045, -0.165],
  },
  {
    'code': 'NS18',
    'name': 'Braddell',
    'site_tag': 'smrt_braddell',
    'coord': [-0.030, -0.130],
  },
  {
    'code': 'NS19',
    'name': 'Toa Payoh',
    'site_tag': 'smrt_toa_payoh',
    'coord': [-0.030, -0.090],
  },
  {
    'code': 'NS20',
    'name': 'Novena',
    'site_tag': 'smrt_novena',
    'coord': [-0.040, -0.050],
  },
  {
    'code': 'NS21',
    'name': 'Newton',
    'site_tag': 'smrt_newton',
    'coord': [-0.085, 0.004],
  },
  {
    'code': 'NS22',
    'name': 'Orchard',
    'site_tag': 'smrt_orchard',
    'coord': [-0.105, 0.070],
  },
  {
    'code': 'NS23',
    'name': 'Somerset',
    'site_tag': 'smrt_somerset',
    'coord': [-0.080, 0.120],
  },
  {
    'code': 'NS24',
    'name': 'Dhoby Ghaut',
    'site_tag': 'smrt_dhoby_ghaut',
    'coord': [-0.055, 0.175],
  },
  {
    'code': 'NS25',
    'name': 'City Hall',
    'site_tag': 'smrt_city_hall',
    'coord': [0.015, 0.285],
  },
  {
    'code': 'NS26',
    'name': 'Raffles Place',
    'site_tag': 'smrt_raffles_place',
    'coord': [0.015, 0.340],
  },
  {
    'code': 'NS27',
    'name': 'Marina Bay',
    'site_tag': 'smrt_marina_bay',
    'coord': [0.030, 0.400],
  },
  {
    'code': 'NS28',
    'name': 'Marina South Pier',
    'site_tag': 'smrt_marina_south_pier',
    'coord': [0.060, 0.440],
  },
];
