const List<Map<String, dynamic>> stationsTE = [
  {
    'code': 'TE1',
    'name': 'Woodlands North',
    'site_tag': 'smrt_woodlands_north',
    'coord': [-0.270, -0.430],
  },
  {
    'code': 'TE2',
    'name': 'Woodlands',
    'site_tag': 'smrt_woodlands',
    'coord': [-0.245, -0.385],
  },
  {
    'code': 'TE3',
    'name': 'Woodlands South',
    'site_tag': 'smrt_woodlands_south',
    'coord': [-0.210, -0.330],
  },
  {
    'code': 'TE4',
    'name': 'Springleaf',
    'site_tag': 'smrt_springleaf',
    'coord': [-0.185, -0.295],
  },
  {
    'code': 'TE5',
    'name': 'Lentor',
    'site_tag': 'smrt_lentor',
    'coord': [-0.172, -0.270],
  },
  {
    'code': 'TE6',
    'name': 'Mayflower',
    'site_tag': 'smrt_mayflower',
    'coord': [-0.155, -0.245],
  },
  {
    'code': 'TE7',
    'name': 'Bright Hill',
    'site_tag': 'smrt_bright_hill',
    'coord': [-0.130, -0.220],
  },
  {
    'code': 'TE8',
    'name': 'Upper Thomson',
    'site_tag': 'smrt_upper_thomson',
    'coord': [-0.123, -0.185],
  },
  {
    'code': 'TE9',
    'name': 'Caldecott',
    'site_tag': 'smrt_caldecott',
    'coord': [-0.105, -0.125],
  },
  {
    'code': 'TE11',
    'name': 'Stevens',
    'site_tag': 'smrt_stevens',
    'coord': [-0.105, -0.045],
  },
  {
    'code': 'TE12',
    'name': 'Napier',
    'site_tag': 'smrt_napier',
    'coord': [-0.123, -0.010],
  },
  {
    'code': 'TE13',
    'name': 'Orchard Boulevard',
    'site_tag': 'smrt_orchard_boulevard',
    'coord': [-0.123, 0.030],
  },
  {
    'code': 'TE14',
    'name': 'Orchard',
    'site_tag': 'smrt_orchard',
    'coord': [-0.133, 0.070],
  },
  {
    'code': 'TE15',
    'name': 'Great World',
    'site_tag': 'smrt_great_world',
    'coord': [-0.123, 0.120],
  },
  {
    'code': 'TE16',
    'name': 'Havelock',
    'site_tag': 'smrt_havelock',
    'coord': [-0.123, 0.175],
  },
  {
    'code': 'TE17',
    'name': 'Outram Park',
    'site_tag': 'smrt_outram_park',
    'coord': [-0.060, 0.285],
  },
  {
    'code': 'TE18',
    'name': 'Maxwell',
    'site_tag': 'smrt_maxwell',
    'coord': [-0.040, 0.330],
  },
  {
    'code': 'TE19',
    'name': 'Shenton Way',
    'site_tag': 'smrt_shenton_way',
    'coord': [-0.000, 0.385],
  },
  {
    'code': 'TE20',
    'name': 'Marina Bay',
    'site_tag': 'smrt_marina_bay',
    'coord': [0.057, 0.400],
  },
  {
    'code': 'TE21',
    'name': 'Gardens by the Bay',
    'site_tag': 'smrt_gardens_by_the_bay',
    'coord': [0.173, 0.365],
  },
];
